# Generated by Django 5.1.1 on 2024-09-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Task',
            new_name='Task_title',
        ),
    ]
